### PR TITLE
New credit card brands (Elo/Hipercard) and icons was added.

### PR DESCRIPTION
**Pull request by tceccatto**
Hi everyone. 

Thanks for the library. It's awesome!

We miss the Elo and Hipercard card brands, so I created this pull request to add them.

This pr add Elo and Hipercard brands to the Credit Card Widget.

### CODE REVIEW

**Comment by ShwetaChauhan18** [comment]
Thanks @tceccatto for your contribution
We will check and let you know

**Comment by tceccatto** [comment]
> Thanks @tceccatto for your contribution We will check and let you know

**Review by ShwetaChauhan18 — APPROVED** [review]

**Comment by tceccatto** [comment]
Thanks for the approval @ShwetaChauhan18 

When a new version of the library will be generated?

**Comment by ShwetaChauhan18** [comment]
> Thanks for the approval @ShwetaChauhan18
> 
> When a new version of the library will be generated?

@tceccatto: We are working on scan feature so, once it's complete we will release new one

**Comment by ShwetaChauhan18** [comment]
@tceccatto : Can you please add this feature change in changelog.md file and create 1 PR

**Comment by tceccatto** [comment]
@ShwetaChauhan18 : it's done: https://github.com/SimformSolutionsPvtLtd/flutter_credit_card/pull/110

**Pull request merged**
