### PR TITLE
Refactor entire class - Use binlist.io to retrieve card information

### PR DESCRIPTION
**Pull request by eudangeld**
• Add more customizable options.
• Simplify usage.

<- See more on- >
*README FILE*

### CODE REVIEW

**Comment by AhsanAyaz** [comment]
This looks cool. It's a pity this was never reviewed.

**Comment by eudangeld** [comment]
@AhsanAyaz 
Check here 
https://github.com/eudangeld/credit_card

**Comment by BirjuVachhani** [comment]
@eudangeld This seems to be closed now.
https://github.com/iannuttall/binlist-data

**Comment by DevarshRanpara** [comment]
@eudangeld there is no support for binlist-data now. So i am closing this PR.
Thank you.

**Pull request closed without merging**
